---
title: "Semi-quantification"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, , message = FALSE, warning = FALSE}
setwd("C:/Users/HelenSepman/OneDrive - Kruvelab/Documents/GitHub/PFOA_semi_quant_HS")
source("code/functions.R")
library(caTools)
library(tidyverse)
library(caret)
library(plotly)
library(cowplot)


## ---- Reading in LC-MS data of calibration solutions ----
Orbitrap_dataset_raw = read_excel_allsheets(filename = "data/Batch 1 Semi Quant w frag.xlsx")

Orbitrap_dataset_raw = Orbitrap_dataset_raw %>% 
  group_by(Compound) %>%
  mutate(Theoretical_amt = case_when(
    Filename == "2020071205-cal21" ~ mean(Theoretical_amt[Filename=="2020071205-cal22"]),
    TRUE ~ Theoretical_amt))%>%
  ungroup() %>%
  filter(Theoretical_amt != "NaN")

## ---- Reading in SMILES for calibration compounds, removing NAs and adducts, mono PAPs, HFPO-DA ----
SMILES_data = read_SMILES(filename = "data/Smiles_for_Target_PFAS_semicolon.csv",
                          compounds_to_be_removed_as_list = c("HFPO-DA", "MeFOSE", "EtFOSE", "10:2 mono PAP", "4:2 mono PAP", "6:2 mono PAP", "8:2 mono PAP"))


```



```{r, message = FALSE, warning = FALSE, echo = FALSE, include=FALSE, results='hide'}
data = Orbitrap_dataset_raw %>%
  left_join(SMILES_data) %>%
  drop_na(SMILES)

SMILES_forHomolog <- data %>%
  select(Compound, SMILES) %>%
  unique()

SMILEs_match <- SMILES_forHomolog %>%
  left_join(SMILES_forHomolog %>%
              select(SMILES, Compound), by = character())

homologs <- SMILEs_match %>%
  group_by(SMILES.x, SMILES.y) %>%
  mutate(pattern_CF2CF2 = is_homologue(SMILES.x, SMILES.y, "F[C+](F)[C+](F)F")) %>% 
  ungroup()

homologs_CF2CF2 <- homologs %>%
  filter(!is.na(pattern_CF2CF2)) %>%
  select(Compound.x, Compound.y, pattern_CF2CF2) %>%
  rename(Compound = Compound.x, 
         Homologue = Compound.y)


#print(xtable(homologs_CF2CF2), type="latex", comment=FALSE) 
```


```{r, warning=FALSE, fig.height=7, fig.width=10, echo=FALSE}
summary_table_CF2_filtered <- read.csv2("C:/Users/HelenSepman/OneDrive - Kruvelab/Helen_phd/Topics_exp_codes/Lara_PFAS/Melanie/summary_table_CF2_withintercept_filtered.csv")


# Print as table
knitr::kable(homologs_CF2CF2)



summary_table_CF2CF2 <- read.csv2("C:/Users/HelenSepman/OneDrive - Kruvelab/Helen_phd/Topics_exp_codes/Lara_PFAS/Melanie/summary_table_CF2CF2_filtered.csv")
summary_table_CF2_filtered <- summary_table_CF2CF2

# Plot of concentrations calculated with predicted IEs vs experimental
IE_c_plot = ggplot(data = summary_table_CF2_filtered)+
  geom_point(mapping = aes(x = Theoretical_conc_uM,
                           y = conc_pred,
                           color = Compound)) +
  scale_y_log10(limits = c(10^-5, 10^0)) +
  scale_x_log10(limits = c(10^-5, 10^0)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_abline(slope = 1, intercept = 1) +
  geom_abline(slope = 1, intercept = -1) +
  theme(aspect.ratio = 1,
        legend.position = "none"
        )

# Plot of concentrations calculated with homologue series compound vs experimental
homolog_c_plot = ggplot(data = summary_table_CF2_filtered)+
  geom_point(mapping = aes(x = Theoretical_conc_uM,
                           y = conc_homolog,
                           color = Compound,
                           text = paste("Homologue used for quantification:", Compound_homolog, sep = " "))) +
  scale_y_log10(limits = c(10^-5, 10^0)) +
  scale_x_log10(limits = c(10^-5, 10^0)) +
  geom_abline(slope = 1, intercept = 0) +
  geom_abline(slope = 1, intercept = 1) +
  geom_abline(slope = 1, intercept = -1) +
  geom_abline(slope = 1, intercept = 1) +
   theme(aspect.ratio = 1,
         legend.position = "none"
         )


# Plot of concentrations calculated with homologue series compound vs experimental
# homolog_c_plot_intercept = ggplot(data = summary_table_CF2_filtered)+
#   geom_point(mapping = aes(x = Theoretical_conc_uM,
#                            y = conc_homolog_withIntercept,
#                            color = Compound,
#                            text = paste("Homologue used for quantification:", Compound_homolog, sep = " "))) +
#   scale_y_log10(limits = c(10^-5, 10^0)) +
#   scale_x_log10(limits = c(10^-5, 10^0)) +
#   geom_abline(slope = 1, intercept = 0) +
#   geom_abline(slope = 1, intercept = 1) +
#   geom_abline(slope = 1, intercept = -1) +
#   geom_abline(slope = 1, intercept = 1) +
#    theme(aspect.ratio = 1#,
#          #legend.position = "none"
#          )

 ggplotly(IE_c_plot)
 ggplotly(homolog_c_plot)
# ggplotly(homolog_c_plot_intercept)

# Comparison
 plot_comp <- plot_grid(IE_c_plot, homolog_c_plot, ncol = 2)
 plot_comp

  ggsave(plot_comp, filename = "plot_comparison.svg", width=16, height=8, units = "cm")

 
 # Error calculations
summary_table_CF2_filtered = summary_table_CF2_filtered %>%
  mutate(error_IE = case_when(
    Theoretical_conc_uM > conc_pred ~ Theoretical_conc_uM/conc_pred,
    TRUE ~ conc_pred/Theoretical_conc_uM),
    error_homolog = case_when(
      Theoretical_conc_uM > conc_homolog ~ Theoretical_conc_uM/conc_homolog,
      TRUE ~ conc_homolog/Theoretical_conc_uM),)

summary_table_CF2_filtered %>%
  na.omit() %>%
  group_by(pattern) %>%
  summarize(error_IE = mean(error_IE),
            error_homolog = mean(error_homolog)) %>%
  ungroup()

```
